### PR TITLE
adding regional map in plot_global_map

### PR DESCRIPTION
**Pull request by fmagnoni**
9703873 9p_zt inv

### CODE REVIEW

**Comment by wjlei1990** [comment]
Hi, the code doesn't pass through the PEP8 formatting check. Check the link above. Would you mind modify it?

**Comment by wjlei1990** [comment]
Btw, you can always run those tests locally:

```
cd pycmt3d
py.test
```

**Comment by fmagnoni** [comment]
PEP8 ready

**Comment by wjlei1990** [comment]
Oops sorry, there is still some formatting issue. What do you think? I can merge it and modify myself, or you can modify it. Anyway you like.

Let me know.

**Pull request merged**
